import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CarContextProvider from "./context/CarContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <header className="h-10 bg-violet-200 sticky"></header>
          <div className="flex-grow bg-gray-100">
            <CarContextProvider>{children}</CarContextProvider>
          </div>
          <footer className="h-10 bg-violet-200"></footer>
        </div>
      </body>
    </html>
  );
}
